name: Python test wokflow
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]
jobs:
  Run-Python-Addition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python job1.py